### ISSUE TITLE
Rename project so it's not confused with OG SSL-Kill-Switch?

### ISSUE THREAD

**Issue by EthanArbuckle** [NyaMisty/ssl-kill-switch3#1]
The name of this project implies it is associated with the creator of SSL Kill Switch 1 and 2. It may be good to rename this project to something unique to avoid confusion; or perhaps open PRs on SSL-Kill-Switch2 with your feature enhancements

**Comment by novitae** [comment]
The creators of the first and second version aren't the same. However, I feel like it it shouldn't be called this way if the repository isn't even active ... I mean, the last commit is from 9 months ago, pretty sad to see all those SSL pinning bypass projects being abandoned.

**Comment by EthanArbuckle** [comment]
1 and 2 were made by the same person. It was under NCC Group's org name for v1 because the author worked there at the time
