### ISSUE TITLE
Non-Jailbreak version which IPA should I inject the dylib file to?

### ISSUE THREAD

**Issue by Michaelmuko94** [NyaMisty/ssl-kill-switch3#6]
I don't understand the instruction as it says inject the dylib to IPA and install
does it mean inject to any IPA? since I tried that but failed

**Comment by TheDauntless** [comment]
Yes, it means injecting into the IPA you want to bypass the SSL Pinning on.

Injecting into IPAs/resigning is a standard process, so any issue you would have there is most likely unrelated to this repo.

**Comment by liambutler-lawrence** [comment]
Hi @TheDauntless, I'm also a little confused by this. I've read all the docs for Sideloadly, but they don't mention my use case anywhere: disabling SSL pinning (a.k.a. from their point of view, applying an arbitrary tweak) in a regular app downloaded from the App Store.

Currently I use the Uncover jailbreak with SSL Kill Switch 2 installed from Cydia, but this doesn't work on iOS 15 or 16.

Is this project (SSL Kill Switch 3) meant to solve the use case above, and if so, how?

Thanks!

**Comment by P5-2005** [comment]
> Hi @TheDauntless, I'm also a little confused by this. I've read all the docs for Sideloadly, but they don't mention my use case anywhere: disabling SSL pinning (a.k.a. from their point of view, applying an arbitrary tweak) in a regular app downloaded from the App Store.
> 
> Currently I use the Uncover jailbreak with SSL Kill Switch 2 installed from Cydia, but this doesn't work on iOS 15 or 16.
> 
> Is this project (SSL Kill Switch 3) meant to solve the use case above, and if so, how?
> 
> Thanks!

the only working env for now is : rootfull jailbreak on ios15/16 using palera1n jailbreak. sileo will have option to install substitue and preferenceloader to make sslkillswitch work again on last ios15/16
rootless with ellekilt(like substrate) tweak will not work even with misty fork

all rootless still not working(for public) for must of us sure

**Comment by NyaMisty** [comment]
It's now working in rootless jb(using +rootless deb) & rootful jb(using +rootful deb) & TrollStore(inject dylib manually using things like ESign) environments.
The reason I didn't update this package before is because Theos's rootless support was released too late.
