### ISSUE TITLE
IPhone OS arm64 cannot be installed

### ISSUE THREAD

**Issue by wuliao6688** [NyaMisty/ssl-kill-switch3#7]
IPhone OS arm64 cannot be installed

**Comment by wuliao6688** [comment]
IOS 16 Sileo NO mobilesubstrate

**Comment by P5-2005** [comment]
it support for now only arm64e

**Comment by NyaMisty** [comment]
Should support both arm64 & arm64e. Tested on iOS 15.4.1 Dopamine & iOS 13 checkra1n
Package updated in release, sorry no repo.
